Solve problems
1.android.util.AndroidRuntimeException: You cannot combine custom titles
with other title featur;
2.cannot find service since the path has changed